# ------------------------------------- build ------------------------------------------

'build tmra-raise':
  stage: build
  needs: []
  script:
    # - cp src/configuration.${APP_ENV}.ts src/configuration.ts
    - cd apps/raise
    - npm pkg set installConfig.hoistingLimits=workspaces
    - yarn workspaces focus
    # skip dbml for faster build
    - yarn prisma generate --generator client
    - yarn nest build
    # ensure Dockerfile COPY not failed: https://stackoverflow.com/a/70097693/122441
    # - mkdir -vp node_modules
    # - ls -F dist/
    - '[ -f "dist/main.js" ] || { ls -F dist/; echo "Error: Build was invalid. apps/raise/dist/main.js must exist after build! Hint: Make sure you only use src/ folder."; exit 1; }'
    - yarn workspaces focus --production
  artifacts:
    paths:
      # - package.json
      # - .pnp.*
      # - .yarnrc.yml
      # - .yarn/cache/
      # - .yarn/unplugged/
      # - apps/pwa/dist/
      # - node_modules/
      - apps/raise/dist/
      - apps/raise/node_modules/
      # - next-i18next.config.js
      # - next.config.js
      # - public/
      # - .next/
    expire_in: 1 week
  # environment:
  #   name: review/$CI_COMMIT_REF_SLUG
  rules:
    - if: '($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event")'
      # changes:
      #   - 'apps/raise/**/*'
    # You can manually trigger the pipeline with APP_NAMES=tmra-raise
    - if: '$APP_NAMES =~ /\btmra-raise\b/'

# ------------------------------------- publish ------------------------------------------

'publish tmra-raise':
  stage: publish
  needs: ['prepare version', 'build tmra-raise']
  variables:
    SERVICE_NAME: tmra-raise
  cache: []
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  script:
    # see https://github.com/GoogleContainerTools/kaniko/issues/1227
    # https://docs.gitlab.com/ee/ci/docker/using_kaniko.html
    - mkdir -p /kaniko/.docker
    # Requires AWS_REGION, AWS_ACCESS_KEY_ID, and AWS_SECRET_ACCESS_KEY in https://gitlab.com/lovia/lovia-billing/-/settings/ci_cd > Variables
    # - echo "{\"credHelpers\":{\"${DOCKER_REGISTRY}\":\"ecr-login\"}, \"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --cache=true --cache-repo="${CI_REGISTRY_IMAGE}"
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/apps/raise/Dockerfile"
      --build-arg=APP_VERSION="${APP_VERSION}"
      --destination "${CI_REGISTRY_IMAGE}/${SERVICE_NAME}:${APP_VERSION}"
      --destination "${CI_REGISTRY_IMAGE}/${SERVICE_NAME}:${APP_ENV}"
  rules:
    - if: '$CI_COMMIT_BRANCH == "stack/dev" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event")'
    - if: '$CI_COMMIT_BRANCH == "stack/dev" && $APP_NAMES =~ /\btmra-raise\b/'
    - if: '$CI_COMMIT_BRANCH == "stack/staging" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event")'
    - if: '$CI_COMMIT_BRANCH == "stack/staging" && $APP_NAMES =~ /\btmra-raise\b/'
    - if: '$CI_COMMIT_BRANCH == "stack/prod" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event")'
    - if: '$CI_COMMIT_BRANCH == "stack/prod" && $APP_NAMES =~ /\btmra-raise\b/'

# ------------------------------------- trigger-deploy ------------------------------------------

'trigger deploy tmra-raise to dev':
  stage: deploy
  needs:
    - job: prepare version
    - job: build tmra-raise
      artifacts: false
    - job: publish tmra-raise
  variables:
    SERVICE_NAME: tmra-raise
    SERVICE_BUILD_ENV: dev
  cache: []
  image: curlimages/curl
  script:
    - echo "Deploying '$SERVICE_NAME' version '$SERVICE_VERSION' to environment '$SERVICE_BUILD_ENV' ..."
    - >-
      curl --fail-with-body
      --form token=$CI_JOB_TOKEN
      --form ref=main
      --form "variables[APP_NAMES]=$SERVICE_NAME"
      --form "variables[SERVICE_ENV]=$SERVICE_BUILD_ENV"
      --form "variables[SERVICE_VERSION]=$SERVICE_VERSION"
      "https://gitlab.com/api/v4/projects/$DEVSECOPS_PROJECT_ID/trigger/pipeline"
  environment:
    name: $SERVICE_NAME-$SERVICE_BUILD_ENV
    url: https://raise-${SERVICE_BUILD_ENV}.tmra.io
  rules:
    - if: '$CI_COMMIT_BRANCH == "stack/dev" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event")'
    - if: '$CI_COMMIT_BRANCH == "stack/dev" && $APP_NAMES =~ /\btmra-raise\b/'

'trigger deploy tmra-raise to staging':
  stage: deploy
  needs:
    - job: prepare version
    - job: build tmra-raise
      artifacts: false
    - job: publish tmra-raise
  variables:
    SERVICE_NAME: tmra-raise
    SERVICE_BUILD_ENV: staging
  cache: []
  image: curlimages/curl
  script:
    - echo "Deploying '$SERVICE_NAME' version '$SERVICE_VERSION' to environment '$SERVICE_BUILD_ENV' ..."
    - >-
      curl --fail-with-body
      --form token=$CI_JOB_TOKEN
      --form ref=main
      --form "variables[APP_NAMES]=$SERVICE_NAME"
      --form "variables[SERVICE_ENV]=$SERVICE_BUILD_ENV"
      --form "variables[SERVICE_VERSION]=$SERVICE_VERSION"
      "https://gitlab.com/api/v4/projects/$DEVSECOPS_PROJECT_ID/trigger/pipeline"
  environment:
    name: $SERVICE_NAME-$SERVICE_BUILD_ENV
    url: https://raise-${SERVICE_BUILD_ENV}.tmra.io
  rules:
    - if: '$CI_COMMIT_BRANCH == "stack/staging" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event")'
    - if: '$CI_COMMIT_BRANCH == "stack/staging" && $APP_NAMES =~ /\btmra-raise\b/'

'trigger deploy tmra-raise to prod':
  stage: deploy
  needs:
    - job: prepare version
    - job: build tmra-raise
      artifacts: false
    - job: publish tmra-raise
  variables:
    SERVICE_NAME: tmra-raise
    SERVICE_BUILD_ENV: prod
  cache: []
  image: curlimages/curl
  script:
    - echo "Deploying '$SERVICE_NAME' version '$SERVICE_VERSION' to environment '$SERVICE_BUILD_ENV' ..."
    - >-
      curl --fail-with-body
      --form token=$CI_JOB_TOKEN
      --form ref=main
      --form "variables[APP_NAMES]=$SERVICE_NAME"
      --form "variables[SERVICE_ENV]=$SERVICE_BUILD_ENV"
      --form "variables[SERVICE_VERSION]=$SERVICE_VERSION"
      "https://gitlab.com/api/v4/projects/$DEVSECOPS_PROJECT_ID/trigger/pipeline"
  environment:
    name: $SERVICE_NAME-$SERVICE_BUILD_ENV
    url: https://raise.tmra.io
  rules:
    - if: '$CI_COMMIT_BRANCH == "stack/prod" && ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event")'
    - if: '$CI_COMMIT_BRANCH == "stack/prod" && $APP_NAMES =~ /\btmra-raise\b/'
