export type IPaymentIntent = {
  id?: string;
  object?: string;
  amount?: number;
  amount_capturable?: number;
  amount_details?: any | null;
  amount_received?: number;
  application?: any | null;
  application_fee_amount?: any | null;
  automatic_payment_methods?: any | null;
  canceled_at?: any | null;
  cancellation_reason?: any | null;
  capture_method?: string;
  client_secret?: string;
  confirmation_method?: string;
  currency?: string;
  customer?: string;
  description?: string;
  created?: number | Date;
  livemode?: boolean;
  invoice?: any | null;
  last_payment_error?: any | null;
  latest_charge?: any | null;
  metadata?: any | null;
  next_action?: any | null;
  on_behalf_of?: any | null;
  payment_method?: any | null;
  payment_method_options?: any | null;
  payment_method_types?: any[] | [];
  processing?: any | null;
  review?: any | null;
  setup_future_usage?: any | null;
  shipping?: any | null;
  source?: any | null;
  statement_descriptor?: any | null;
  statement_descriptor_suffix?: any | null;
  transfer_data?: any | null;
  transfer_group?: any | null;
  receipt_email?: string | null;
  status?: string | null;
};
