nmMode: hardlinks-local

nodeLinker: node-modules

packageExtensions:
  "@metinseylan/nestjs-opentelemetry@*":
    dependencies:
      "@opentelemetry/api-metrics": "*"
      "@opentelemetry/sdk-metrics-base": "*"
  "@opentelemetry/resource-detector-gcp@*":
    dependencies:
      "@opentelemetry/core": "*"
  "@opentelemetry/sdk-node@*":
    dependencies:
      "@opentelemetry/semantic-conventions": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.3.1.cjs
