import { Prisma } from '@prisma/client';

export type InnerStatus =
  | 'ACCEPTED_BY_MODERATOR'
  | 'CREATED_BY_CLIENT'
  | 'ASKING_MODERATOR_CHANGES'
  | 'ASKING_CLIENT_CHANGES'
  | 'REJECTED_BY_MODERATOR'
  | 'REVISED_BY_PROJECT_MANAGER'
  | 'INCORRECT_PAYMENT_DETAIL'
  | 'PAYMENT_DETAIL_REVISIED_BY_SUPERVISOR'
  | 'REJECTED_BY_SUPERVISOR_WITH_COMMENT'
  | 'ACCEPTED_BY_SUPERVISOR'
  | 'ACCEPTED_AND_SETUP_PAYMENT_BY_SUPERVISOR'
  | 'NEED_REPORT_BY_CLIENT'
  | 'CLIENT_UPLOAD_REPORT'
  | 'ASKING_SUPERVISOR_CHANGES'
  | 'ACCEPTED_AND_NEED_CONSULTANT'
  | 'REJECTED_BY_CONSULTANT'
  | 'ACCEPTED_BY_CONSULTANT'
  | 'ASKING_PROJECT_MANAGER_CHANGES'
  | 'REJECTED_BY_CEO_WITH_COMMENT'
  | 'ACCEPTED_BY_CEO_FOR_PAYMENT_SPESIFICATION'
  | 'ACCEPTED_BY_FOR_PAYMENT_SPESIFICATION'
  | 'ASKING_PROJECT_SUPERVISOR_CHANGES'
  | 'ACCEPTED_BY_FINACE'
  | 'DONE_BY_CACHIER'
  | 'ACCEPTED_BY_PROJECT_MANAGER'
  | 'PAYMENT_SPECIFICATION_BY_SUPERVISOR'
  | 'PROJECT_COMPLETED'
  | 'REJECTED_BY_PROJECT_MANAGER_WITH_COMMENT'
  | 'REVISED_BY_CLIENT';

export type OutterStatus = 'COMPLETED' | 'PENDING' | 'CANCELED' | 'ONGOING';

export type ProposalItemBudget = {
  id: string;
  proposal_id: string;
  amount: Prisma.Decimal;
  clause: string;
  explanation: string;
};
