export const PROJECT_MANAGEMENT = [
  {
    project_number: '#768873',
    project_name: 'Maintenance Project of the New Industrial Call Society Mosque in Riyadh',
    associaton_name: 'New Industrial Call Society in Riyadh',
    section: 'Mosque Department',
    createdAt: '2022-09-23T17:00:00.000Z',
  },
  {
    project_number: '#768873',
    project_name: 'Maintenance Project of the New Industrial Call Society Mosque in Riyadh',
    associaton_name: 'New Industrial Call Society in Riyadh',
    section: 'Facilitated Scholarship Track',
    createdAt: '2022-09-23T17:00:00.000Z',
  },
  {
    project_number: '#768873',
    project_name: 'Maintenance Project of the New Industrial Call Society Mosque in Riyadh',
    associaton_name: 'New Industrial Call Society in Riyadh',
    section: 'Mosque Department',
    createdAt: '2022-09-23T17:00:00.000Z',
  },
  {
    project_number: '#768873',
    project_name: 'Maintenance Project of the New Industrial Call Society Mosque in Riyadh',
    associaton_name: 'New Industrial Call Society in Riyadh',
    section: 'Initiatives Track',
    createdAt: '2022-09-23T17:00:00.000Z',
  },
  {
    project_number: '#768873',
    project_name: 'Maintenance Project of the New Industrial Call Society Mosque in Riyadh',
    associaton_name: 'New Industrial Call Society in Riyadh',
    section: 'baptismal Track',
    createdAt: '2022-09-23T17:00:00.000Z',
  },
  {
    project_number: '#768873',
    project_name: 'Maintenance Project of the New Industrial Call Society Mosque in Riyadh',
    associaton_name: 'New Industrial Call Society in Riyadh',
    section: "Sheik'h path",
    createdAt: '2022-09-23T17:00:00.000Z',
  },
  {
    project_number: '#768873',
    project_name: 'Maintenance Project of the New Industrial Call Society Mosque in Riyadh',
    associaton_name: 'New Industrial Call Society in Riyadh',
    section: 'Mosque Department',
    createdAt: '2022-09-23T17:00:00.000Z',
  },
  {
    project_number: '#768873',
    project_name: 'Maintenance Project of the New Industrial Call Society Mosque in Riyadh',
    associaton_name: 'New Industrial Call Society in Riyadh',
    section: 'Facilitated Scholarship Track',
    createdAt: '2022-09-23T17:00:00.000Z',
  },
  {
    project_number: '#768873',
    project_name: 'Maintenance Project of the New Industrial Call Society Mosque in Riyadh',
    associaton_name: 'New Industrial Call Society in Riyadh',
    section: 'Mosque Department',
    createdAt: '2022-09-23T17:00:00.000Z',
  },
];
