export const PERMISSIONS = [
  'CEO',
  'PROJECT_MANAGER',
  'PROJECT_SUPERVISOR',
  'CONSULTANT',
  'FINANCE',
  'CASHIER',
  'MODERATOR',
  'ACCOUNTS_MANAGER',
  'ADMIN',
  'AUDITOR_REPORT',
  'PORTAL_REPORT',
];
